### PR TITLE
Autolink sftp and ftps protocols

### PR DESCRIPTION
**Pull request by marius-balteanu**
Currently, only ftp protocol is auto linked. This PR is adding also sftp and ftps protocols.

Also, is adding a test for the ftp protocol.

### CODE REVIEW

**Comment by marius-balteanu** [comment]
@kivikakk, is there anything I can do in order to have this PR accepted?

**Comment by marius-balteanu** [comment]
A little bit of context, I made a quick integration of this library in Redmine in order to switch from the custom implementation of auto link (https://github.com/redmine/redmine/blob/master/lib/redmine/wiki_formatting.rb#L135) and when I ran the test suite I've observed that these protocols are not auto linked as Redmine already supports them.

**Comment by kivikakk** [comment]
Rinku is essentially in maintenance mode -- at this stage we're not accepting new features or changes in behaviour that aren't bug fixes as we're unwilling to provide ongoing maintenance support for them. I'd suggest forking!

**Comment by marius-balteanu** [comment]
I didn't know this, thanks for your response!

**Pull request closed without merging**
